# Generated by Django 3.2.9 on 2021-11-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
